// 한국어 주석: lib.rs는 Tauri 진입점만 남기고 실제 구현은 기능별 include 파일로 분리한다.
mod features;

include!("lib_parts/01_imports_and_core_types.rs");
include!("lib_parts/02_native_reports_and_preferences.rs");
include!("lib_parts/03_provider_and_git_types.rs");
include!("lib_parts/04_decision_types_and_constants.rs");
include!("lib_parts/05_adapter_catalog_and_probe_commands.rs");
include!("lib_parts/06_task_records_and_front_commands.rs");
include!("lib_parts/07_cli_session_runtime.rs");
include!("lib_parts/08_session_io_and_workspace_commands.rs");
include!("lib_parts/09_workspace_resource_cache.rs");
include!("lib_parts/10_decision_commands_and_app_run.rs");
include!("lib_parts/11_adapter_health_and_processes.rs");
include!("lib_parts/12_native_process_actions.rs");
include!("lib_parts/13_pty_runtime_and_output.rs");
include!("lib_parts/14_task_run_persistence.rs");
include!("lib_parts/15_runtime_data_overview.rs");
include!("lib_parts/16_data_stats_and_factory.rs");
include!("lib_parts/17_payload_support_and_utilities.rs");
include!("lib_parts/18_source_and_decision_detection.rs");
include!("lib_parts/19_decision_inbox_helpers.rs");
include!("lib_parts/20_preferences_and_clipboard_helpers.rs");
include!("lib_parts/21_subagent_plan_runtime.rs");
include!("lib_parts/22_subagent_fanout_runtime.rs");
include!("lib_parts/23_workspace_state_and_git_status.rs");
include!("lib_parts/24_git_actions_and_workspace_state.rs");
include!("lib_parts/25_git_reports_and_paths.rs");
include!("lib_parts/26_git_mutation_helpers.rs");
include!("lib_parts/27_workspace_paths_and_command_resolution.rs");
include!("lib_parts/28_tests.rs");
