import type { NativePtyQuickCommand, RuntimeTerminalLanguage } from "./runtimeTerminalTypes";

export const terminalCopy = {
  ko: {
    launcher: "터미널",
    close: "터미널 닫기",
    aria: "하단 다중 CLI 터미널",
    eyebrow: "실행 보드",
    title: "하단 다중 CLI 터미널",
    collapse: "접기",
    sessions: "세션",
    activeLanes: "실행 중",
    deferredLanes: "보류",
    autoDeferred: "자동 보류",
    output: "출력",
    events: "이벤트",
    rail: "터미널 상태와 보기 선택",
    intake: "입력",
    decision: "결정함",
    review: "검토",
    diffPending: "diff 대기",
    clean: "정리됨",
    start: "시작",
    native: "PTY",
    nativePty: "네이티브 PTY",
    nativePtyDetail: "OS pseudo terminal + xterm.js",
    startNativePty: "PTY 셸 시작",
    refreshNativePty: "PTY 새로고침",
    stopNativePty: "PTY 중단",
    nativePtySurface: "네이티브 PTY 터미널",
    nativePtyPlaceholder: "PTY 셸을 시작하면 여기에서 실제 터미널 입출력이 렌더링됩니다.",
    terminalSearch: "검색",
    terminalSearchPlaceholder: "출력 검색",
    terminalSearchPrevious: "이전",
    terminalSearchNext: "다음",
    terminalCopySelection: "선택 복사",
    terminalCopyOutput: "출력 복사",
    terminalPaste: "붙여넣기",
    terminalClear: "화면 정리",
    terminalFit: "맞춤",
    terminalQuickCommands: "빠른 명령",
    terminalCopied: "복사됨",
    terminalCopyFailed: "복사할 내용이 없거나 권한이 없습니다.",
    terminalPasted: "붙여넣음",
    terminalPasteBlocked: "클립보드 읽기 권한이 없거나 붙여넣을 수 없습니다.",
    terminalCleared: "터미널 화면을 정리했습니다.",
    terminalFitted: "터미널 크기를 다시 맞췄습니다.",
    terminalSearchMatch: "검색 결과로 이동했습니다.",
    terminalSearchNoMatch: "일치하는 출력이 없습니다.",
    terminalCommandSent: "명령을 보냈습니다.",
    terminalGuidePty: "PTY 셸",
    terminalGuidePtyDetail: "실제 OS 셸을 앱 안에서 시작",
    terminalGuideCwd: "작업 폴더",
    terminalGuideCwdDetail: "루트/프로젝트/사용자 지정 경로 선택",
    terminalGuideControls: "검색과 클립보드",
    terminalGuideControlsDetail: "Cmd/Ctrl+F, Shift+C/V, 화면 정리",
    terminalGuideAccount: "AI 계정",
    terminalGuideAccountDetail: "설정에서 GPT/Gemini 키 연결",
    terminalGuideCli: "CLI 자동 설정",
    terminalGuideCliDetail: "원클릭으로 awp CLI 설치와 PATH 등록",
    blocked: "막힘",
    ready: "준비됨",
    adapter: "어댑터",
    mode: "모드",
    questions: "질문",
    autoDefer: "자동 보류",
    manual: "수동",
    changeInit: "초기화 설정 변경",
    workingDir: "작업 폴더",
    initialInput: "초기 입력",
    starting: "시작 중",
    startSession: "세션 시작",
    savePrompt: "선택 프롬프트 저장",
    resetPrompt: "기본값",
    promptDefault: "기본 프롬프트",
    promptCustomized: "수정된 프롬프트",
    noSessions: "실행 세션이 없습니다. 설정에서 어댑터를 확인한 뒤 세션을 시작하세요.",
    sessionList: "CLI 세션 목록",
    inspect: "보기",
    poll: "새로고침",
    defer: "질문 보류",
    cancel: "중단",
    noCode: "코드 없음",
    recordPending: "기록 대기",
    stdoutPending: "stdout 로그 대기",
    selectedOutput: "선택한 CLI 출력",
    noSession: "세션 없음",
    sessionOutput: "세션 출력",
    idle: "대기",
    noOutput: "아직 출력이 없습니다",
    send: "보내기",
    eventList: "터미널 이벤트 목록",
    noEvents: "구조화된 터미널 이벤트가 아직 없습니다."
  },
  en: {
    launcher: "Terminal",
    close: "Close terminal",
    aria: "Bottom multi-CLI terminal",
    eyebrow: "Run Board",
    title: "Bottom multi-CLI terminal",
    collapse: "Collapse",
    sessions: "Sessions",
    activeLanes: "active lanes",
    deferredLanes: "deferred lanes",
    autoDeferred: "auto deferred",
    output: "output",
    events: "events",
    rail: "Terminal state and view selector",
    intake: "intake",
    decision: "decision",
    review: "review",
    diffPending: "diff pending",
    clean: "clean",
    start: "Start",
    native: "PTY",
    nativePty: "Native PTY",
    nativePtyDetail: "OS pseudo terminal + xterm.js",
    startNativePty: "Start PTY Shell",
    refreshNativePty: "Poll PTY",
    stopNativePty: "Stop PTY",
    nativePtySurface: "Native PTY terminal",
    nativePtyPlaceholder: "Start a PTY shell to render real terminal I/O here.",
    terminalSearch: "Search",
    terminalSearchPlaceholder: "Search output",
    terminalSearchPrevious: "Previous",
    terminalSearchNext: "Next",
    terminalCopySelection: "Copy selection",
    terminalCopyOutput: "Copy output",
    terminalPaste: "Paste",
    terminalClear: "Clear screen",
    terminalFit: "Fit",
    terminalQuickCommands: "Quick commands",
    terminalCopied: "Copied",
    terminalCopyFailed: "Nothing to copy or clipboard permission is blocked.",
    terminalPasted: "Pasted",
    terminalPasteBlocked: "Clipboard read is unavailable or this terminal cannot receive input.",
    terminalCleared: "Terminal screen cleared.",
    terminalFitted: "Terminal size refit.",
    terminalSearchMatch: "Moved to search match.",
    terminalSearchNoMatch: "No matching output.",
    terminalCommandSent: "Command sent.",
    terminalGuidePty: "PTY shell",
    terminalGuidePtyDetail: "Start the real OS shell inside the app",
    terminalGuideCwd: "Working folder",
    terminalGuideCwdDetail: "Choose root, project, or custom path",
    terminalGuideControls: "Search and clipboard",
    terminalGuideControlsDetail: "Cmd/Ctrl+F, Shift+C/V, clear screen",
    terminalGuideAccount: "AI accounts",
    terminalGuideAccountDetail: "Connect GPT/Gemini keys in Settings",
    terminalGuideCli: "CLI Auto Setup",
    terminalGuideCliDetail: "One-click install AWP CLI and PATH",
    blocked: "blocked",
    ready: "ready",
    adapter: "Adapter",
    mode: "Mode",
    questions: "Questions",
    autoDefer: "auto-defer",
    manual: "manual",
    changeInit: "Change init settings",
    workingDir: "Working dir",
    initialInput: "Initial input",
    starting: "Starting",
    startSession: "Start Session",
    savePrompt: "Save selected prompt",
    resetPrompt: "Default",
    promptDefault: "Default prompt",
    promptCustomized: "Customized prompt",
    noSessions: "No run sessions. Check the adapter in Settings, then start a session.",
    sessionList: "CLI session list",
    inspect: "Inspect",
    poll: "Poll",
    defer: "Defer",
    cancel: "Cancel",
    noCode: "no code",
    recordPending: "record pending",
    stdoutPending: "stdout log pending",
    selectedOutput: "Selected CLI output",
    noSession: "no-session",
    sessionOutput: "Session output",
    idle: "idle",
    noOutput: "No output yet",
    send: "Send",
    eventList: "Terminal event list",
    noEvents: "No structured terminal events yet."
  }
} satisfies Record<RuntimeTerminalLanguage, Record<string, string>>;

export const nativePtyQuickActions = {
  ko: [
    { id: "codex", label: "Codex", detail: "codex", input: "codex\n" },
    { id: "pwd", label: "현재 위치", detail: "pwd", input: "pwd\n" },
    { id: "list", label: "파일 목록", detail: "ls -la", input: "ls -la\n" },
    { id: "git", label: "Git 상태", detail: "git status --short", input: "git status --short\n" }
  ],
  en: [
    { id: "codex", label: "Codex", detail: "codex", input: "codex\n" },
    { id: "pwd", label: "Current dir", detail: "pwd", input: "pwd\n" },
    { id: "list", label: "List files", detail: "ls -la", input: "ls -la\n" },
    { id: "git", label: "Git status", detail: "git status --short", input: "git status --short\n" }
  ]
} satisfies Record<RuntimeTerminalLanguage, NativePtyQuickCommand[]>;
