from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


IGNORE_DIRS = {
    ".git",
    ".next",
    ".pytest_cache",
    "__pycache__",
    ".venv",
    "venv",
    "node_modules",
    "dist",
    "build",
    "coverage",
    "out",
}

ROOT_PURPOSES = {
    "_ops": "operations hub, prompts, workflows, and maps",
    "_docs": "workspace-level rules, decisions, and operating docs",
    "_philosophy": "foundational agent and platform operating philosophy",
    "_history": "dated work logs and compressed context",
    "_research": "reusable internet research and external reference notes",
    "_skills": "tracked source for custom Codex skills",
    "_templates": "reusable project and artifact templates",
    "_tools": "local tools that reduce repeated work",
    "_archive": "paused or retired projects",
    "agent-platform": "core personal agent-building platform project",
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate operations maps.")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[3])
    parser.add_argument("--check", action="store_true", help="Fail if maps are stale.")
    args = parser.parse_args(argv)

    root = args.root.resolve()
    outputs = {
        root / "_ops" / "maps" / "repository-map.md": render_repository_map(root),
        root / "_ops" / "maps" / "prompt-map.md": render_prompt_map(root),
    }

    stale = []
    for path, content in outputs.items():
        normalized = content.rstrip() + "\n"
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != normalized:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(normalized, encoding="utf-8")

    if args.check and stale:
        for path in stale:
            print(f"stale: {path.relative_to(root)}", file=sys.stderr)
        return 1

    if not args.check:
        for path in outputs:
            print(f"updated: {path.relative_to(root)}")
    return 0


def render_repository_map(root: Path) -> str:
    ignored_parts = IGNORE_DIRS | load_generated_ignore_parts(root)
    files = sorted(
        path.relative_to(root)
        for path in root.rglob("*")
        if path.is_file() and not should_ignore_with_parts(path.relative_to(root), ignored_parts)
    )
    root_entries = sorted(path for path in root.iterdir() if path.is_dir() and path.name not in ignored_parts)
    root_metadata = load_root_folder_metadata(root)

    lines = [
        "# Repository Map",
        "",
        "Generated by `_tools/workspace-index/src/workspace_index.py`.",
        "",
        "## Root Folders",
        "",
        "| Path | Class | Purpose | Source |",
        "| --- | --- | --- | --- |",
    ]

    for entry in root_entries:
        metadata = root_metadata.get(
            entry.name,
            {
                "class": "unclassified",
                "purpose": "project or workspace folder",
                "source": "workspace-index fallback",
            },
        )
        lines.append(
            f"| `{entry.name}/` | {metadata['class']} | {metadata['purpose']} | {metadata['source']} |"
        )

    lines.extend(
        [
            "",
            "## Key Start Points",
            "",
            "- `_ops/index.md`: operations navigation",
            "- `_ops/prompts/00-router.md`: prompt selection",
            "- `_ops/workflows/00-start-here.md`: default work sequence",
            "- `_docs/instructions/persistent-instructions.md`: durable user instructions",
            "- `agent-platform/README.md`: platform project overview",
            "",
            "## File Index",
            "",
        ]
    )

    current_group = ""
    for file_path in files:
        group = file_path.parts[0]
        if group != current_group:
            current_group = group
            if lines[-1] != "":
                lines.append("")
            lines.extend([f"### `{group}`", ""])
        lines.append(f"- `{file_path.as_posix()}`")

    return "\n".join(lines)


def load_root_folder_metadata(root: Path) -> dict[str, dict[str, str]]:
    metadata = {
        name: {"class": "known_root", "purpose": purpose, "source": "workspace-index built-in"}
        for name, purpose in ROOT_PURPOSES.items()
    }

    policy_path = root / "_ops" / "projects" / "root-structure-policy.json"
    policy = read_json(policy_path)
    if policy:
        for field_name, class_name in [
            ("reserved_operational_dirs", "reserved_operational"),
            ("local_only_dirs", "local_only"),
            ("runtime_adapter_dirs", "runtime_adapter"),
        ]:
            for item in list_of_dicts(policy.get(field_name, [])):
                name = str(item.get("name", "")).strip()
                if not name:
                    continue
                metadata[name] = {
                    "class": class_name,
                    "purpose": str(item.get("purpose", "")).strip() or metadata.get(name, {}).get("purpose", ""),
                    "source": policy_path.relative_to(root).as_posix(),
                }

    registry_path = root / str(policy.get("project_registry_path", "_ops/projects/registry.json")) if policy else root / "_ops" / "projects" / "registry.json"
    registry = read_json(registry_path)
    for project in list_of_dicts(registry.get("projects", [])):
        project_root = root_folder_name(str(project.get("path", project.get("name", ""))))
        if not project_root:
            continue
        metadata[project_root] = {
            "class": "registered_project",
            "purpose": str(project.get("purpose", "")).strip() or metadata.get(project_root, {}).get("purpose", ""),
            "source": registry_path.relative_to(root).as_posix(),
        }

    return metadata


def render_prompt_map(root: Path) -> str:
    prompt_files = sorted((root / "_ops" / "prompts").glob("*.md"))
    workflow_files = sorted((root / "_ops" / "workflows").glob("*.md"))

    lines = [
        "# Prompt Map",
        "",
        "Generated by `_tools/workspace-index/src/workspace_index.py`.",
        "",
        "## Prompts",
        "",
        "| Prompt | Use When |",
        "| --- | --- |",
    ]

    for path in prompt_files:
        lines.append(f"| `{path.relative_to(root).as_posix()}` | {extract_use_when(path)} |")

    lines.extend(["", "## Workflows", "", "| Workflow | Purpose |", "| --- | --- |"])
    for path in workflow_files:
        lines.append(f"| `{path.relative_to(root).as_posix()}` | {extract_section_summary(path, '## Purpose')} |")

    lines.extend(
        [
            "",
            "## Default Route",
            "",
            "1. `_ops/prompts/00-router.md`",
            "2. Matching prompt file",
            "3. Matching workflow file",
            "4. `_ops/maps/repository-map.md` when location is unclear",
        ]
    )

    return "\n".join(lines)


def should_ignore(relative_path: Path) -> bool:
    return should_ignore_with_parts(relative_path, IGNORE_DIRS)


def should_ignore_with_parts(relative_path: Path, ignored_parts: set[str]) -> bool:
    return any(part in ignored_parts for part in relative_path.parts)


def load_generated_ignore_parts(root: Path) -> set[str]:
    policy_path = root / "_ops" / "projects" / "root-structure-policy.json"
    policy = read_json(policy_path)
    parts = set()
    for item in list_of_dicts(policy.get("generated_output_dirs", [])):
        pattern = str(item.get("pattern", "")).strip().rstrip("/")
        if not pattern:
            continue
        leaf = pattern.split("/")[-1]
        if leaf and "*" not in leaf:
            parts.add(leaf)
    return parts


def read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def list_of_dicts(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, dict)]


def root_folder_name(path_value: str) -> str:
    stripped = path_value.strip().strip("/")
    if not stripped:
        return ""
    return Path(stripped).parts[0]


def extract_use_when(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("Use when:"):
            return line.removeprefix("Use when:").strip()
    return first_heading(path)


def extract_section_summary(path: Path, heading: str) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    for index, line in enumerate(lines):
        if line.strip() == heading:
            for candidate in lines[index + 1 :]:
                candidate = candidate.strip()
                if candidate and not candidate.startswith("#"):
                    return candidate
    return first_heading(path)


def first_heading(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line.removeprefix("# ").strip()
    return path.stem


if __name__ == "__main__":
    raise SystemExit(main())
