from __future__ import annotations

import argparse
import sys
from pathlib import Path


IGNORE_DIRS = {
    ".git",
    ".pytest_cache",
    "__pycache__",
    ".venv",
    "venv",
    "node_modules",
    "dist",
    "build",
    "coverage",
}

ROOT_PURPOSES = {
    "_ops": "operations hub, prompts, workflows, and maps",
    "_docs": "workspace-level rules, decisions, and operating docs",
    "_philosophy": "foundational agent and platform operating philosophy",
    "_history": "dated work logs and compressed context",
    "_research": "reusable internet research and external reference notes",
    "_skills": "tracked source for custom Codex skills",
    "_templates": "reusable project and artifact templates",
    "_tools": "local tools that reduce repeated work",
    "_archive": "paused or retired projects",
    "agent-platform": "core personal agent-building platform project",
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate operations maps.")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[3])
    parser.add_argument("--check", action="store_true", help="Fail if maps are stale.")
    args = parser.parse_args(argv)

    root = args.root.resolve()
    outputs = {
        root / "_ops" / "maps" / "repository-map.md": render_repository_map(root),
        root / "_ops" / "maps" / "prompt-map.md": render_prompt_map(root),
    }

    stale = []
    for path, content in outputs.items():
        normalized = content.rstrip() + "\n"
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != normalized:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(normalized, encoding="utf-8")

    if args.check and stale:
        for path in stale:
            print(f"stale: {path.relative_to(root)}", file=sys.stderr)
        return 1

    if not args.check:
        for path in outputs:
            print(f"updated: {path.relative_to(root)}")
    return 0


def render_repository_map(root: Path) -> str:
    files = sorted(
        path.relative_to(root)
        for path in root.rglob("*")
        if path.is_file() and not should_ignore(path.relative_to(root))
    )
    root_entries = sorted(path for path in root.iterdir() if not path.name.startswith("."))

    lines = [
        "# Repository Map",
        "",
        "Generated by `_tools/workspace-index/src/workspace_index.py`.",
        "",
        "## Root Folders",
        "",
        "| Path | Purpose |",
        "| --- | --- |",
    ]

    for entry in root_entries:
        if entry.is_dir() and entry.name not in IGNORE_DIRS:
            purpose = ROOT_PURPOSES.get(entry.name, "project or workspace folder")
            lines.append(f"| `{entry.name}/` | {purpose} |")

    lines.extend(
        [
            "",
            "## Key Start Points",
            "",
            "- `_ops/index.md`: operations navigation",
            "- `_ops/prompts/00-router.md`: prompt selection",
            "- `_ops/workflows/00-start-here.md`: default work sequence",
            "- `_docs/instructions/persistent-instructions.md`: durable user instructions",
            "- `agent-platform/README.md`: platform project overview",
            "",
            "## File Index",
            "",
        ]
    )

    current_group = ""
    for file_path in files:
        group = file_path.parts[0]
        if group != current_group:
            current_group = group
            if lines[-1] != "":
                lines.append("")
            lines.extend([f"### `{group}`", ""])
        lines.append(f"- `{file_path.as_posix()}`")

    return "\n".join(lines)


def render_prompt_map(root: Path) -> str:
    prompt_files = sorted((root / "_ops" / "prompts").glob("*.md"))
    workflow_files = sorted((root / "_ops" / "workflows").glob("*.md"))

    lines = [
        "# Prompt Map",
        "",
        "Generated by `_tools/workspace-index/src/workspace_index.py`.",
        "",
        "## Prompts",
        "",
        "| Prompt | Use When |",
        "| --- | --- |",
    ]

    for path in prompt_files:
        lines.append(f"| `{path.relative_to(root).as_posix()}` | {extract_use_when(path)} |")

    lines.extend(["", "## Workflows", "", "| Workflow | Purpose |", "| --- | --- |"])
    for path in workflow_files:
        lines.append(f"| `{path.relative_to(root).as_posix()}` | {extract_section_summary(path, '## Purpose')} |")

    lines.extend(
        [
            "",
            "## Default Route",
            "",
            "1. `_ops/prompts/00-router.md`",
            "2. Matching prompt file",
            "3. Matching workflow file",
            "4. `_ops/maps/repository-map.md` when location is unclear",
        ]
    )

    return "\n".join(lines)


def should_ignore(relative_path: Path) -> bool:
    return any(part in IGNORE_DIRS for part in relative_path.parts)


def extract_use_when(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("Use when:"):
            return line.removeprefix("Use when:").strip()
    return first_heading(path)


def extract_section_summary(path: Path, heading: str) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    for index, line in enumerate(lines):
        if line.strip() == heading:
            for candidate in lines[index + 1 :]:
                candidate = candidate.strip()
                if candidate and not candidate.startswith("#"):
                    return candidate
    return first_heading(path)


def first_heading(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line.removeprefix("# ").strip()
    return path.stem


if __name__ == "__main__":
    raise SystemExit(main())
