import type { UiLanguage } from "@/types/desktop";

export const nativeWorkspaceCopy = {
  ko: {
    eyebrow: "작업공간 Explorer",
    title: "파일시스템을 끌어와서 처리하기",
    description:
      "왼쪽 탐색기에서 실제 작업공간 파일 시스템을 확인하고, 오른쪽 편집기에서 파일을 열어 수정/저장합니다.",
    chooseFolder: "작업공간 접근 권한 요청",
    choosingFolder: "권한 요청 중",
    permissionDetail: "네이티브 폴더 선택 창에서 허용하면 이 앱이 해당 작업공간을 바로 읽고 저장합니다.",
    permissionGranted: "작업공간 접근 권한을 받았습니다.",
    refreshWorkspace: "작업공간 새로고침",
    refreshFiles: "파일 목록 새로고침",
    openSelected: "선택 파일 열기",
    saveCurrent: "현재 파일 저장",
    saveAll: "열린 변경 모두 저장",
    copyFile: "내용 복사",
    activeWorkspace: "현재 작업공간",
    workspaceState: "작업공간 상태",
    folderSource: "선택 방식",
    fileSearch: "파일명, 폴더, 언어 검색",
    fileList: "파일 목록",
    fileTree: "파일 트리",
    uploadDropzone: "작업공간 접근 권한 요청",
    uploadDropzoneDetail: "네이티브 폴더 선택 창에서 허용하면 탐색기가 실제 파일 시스템을 읽고 편집/저장에 바로 사용합니다.",
    explorerHint: "탐색기에서 파일을 누르면 오른쪽 편집기에 열립니다.",
    openedDrafts: "열린 파일",
    editorSettings: "편집 설정",
    wordWrap: "줄바꿈",
    minimap: "미니맵",
    foldAll: "코드 접기",
    unfoldAll: "코드 펼치기",
    diffMode: "변경 비교",
    editMode: "편집",
    noRuntime: "Tauri 런타임이 없어서 저장은 비활성화됩니다. 지금은 스냅샷 파일만 볼 수 있습니다.",
    noFiles: "표시할 파일이 없습니다. 작업공간 폴더를 선택하거나 검색어를 바꿔보세요.",
    noFileOpen: "왼쪽 파일 목록에서 파일을 클릭하세요.",
    savedWithBackup: "저장 완료. 백업 파일을 만들었습니다.",
    chooseCanceled: "폴더 선택을 취소했습니다.",
    fallbackSource: "스냅샷 대체 데이터",
    runtimeSource: "실제 작업공간",
    dirty: "수정됨",
    clean: "변경 없음",
    loading: "불러오는 중",
    saving: "저장 중"
  },
  en: {
    eyebrow: "Workspace Explorer",
    title: "Bring the filesystem into the platform",
    description:
      "Like VS Code, the left Explorer owns the real workspace filesystem and the editor on the right opens files for processing and saving.",
    chooseFolder: "Request Workspace Access",
    choosingFolder: "Requesting Access",
    permissionDetail: "Use the native folder picker to grant this app access to the workspace for reading and saving.",
    permissionGranted: "Workspace access granted.",
    refreshWorkspace: "Refresh Workspace",
    refreshFiles: "Refresh Files",
    openSelected: "Open Selected",
    saveCurrent: "Save Current",
    saveAll: "Save All Open Changes",
    copyFile: "Copy Content",
    activeWorkspace: "Active Workspace",
    workspaceState: "Workspace State",
    folderSource: "Source",
    fileSearch: "Search file, folder, or language",
    fileList: "File List",
    fileTree: "File Tree",
    uploadDropzone: "Request workspace access",
    uploadDropzoneDetail: "Grant access from the native folder picker, then the Explorer can read, edit, and save real workspace files.",
    explorerHint: "Click a file in Explorer to open it in the editor.",
    openedDrafts: "Open Files",
    editorSettings: "Editor Settings",
    wordWrap: "Word Wrap",
    minimap: "Minimap",
    foldAll: "Fold Code",
    unfoldAll: "Unfold Code",
    diffMode: "Diff",
    editMode: "Edit",
    noRuntime: "Tauri runtime is unavailable. Saving is disabled and snapshot files are shown as fallback.",
    noFiles: "No files to show. Choose a workspace folder or change the search text.",
    noFileOpen: "Click a file from the list on the left.",
    savedWithBackup: "Saved with a backup file.",
    chooseCanceled: "Folder selection was canceled.",
    fallbackSource: "snapshot fallback",
    runtimeSource: "real workspace",
    dirty: "dirty",
    clean: "clean",
    loading: "loading",
    saving: "saving"
  }
} satisfies Record<UiLanguage, Record<string, string>>;
